name: niu_guardian
description: "Aplicación móvil para el registro dinámico de responsables y menores con lógica de validación y generación de códigos únicos."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Iconos
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  flutter_svg: ^2.2.0

  #Control y manejo de estados y rutas
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0

  # Base de Datos Local
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5

  # Formularios y Validaciones
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.2
  shared_preferences: ^2.5.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/niu_square.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/niu_square.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/logo/niu_square.png"
    icon_size: 48

  # Generación de Código (Necesario para Isar)
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo/niu_square.png
  android_12:
    image: assets/logo/niu_square.png
    color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/logo/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
